### ISSUE TITLE
Can I find a Cobalt Strike Profile?

### ISSUE THREAD

**Issue by notalkingya** [lum8rjack/caddy-c2#1]
Can I find a Cobalt Strike Profile?

**Comment by lum8rjack** [comment]
Are you looking for an example Cobalt Strike profile or what is your ask? There is an example profile in  the "tests/profiles" directory.

**Comment by notalkingya** [comment]
> Are you looking for an example Cobalt Strike profile or what is your ask? There is an example profile in the "tests/profiles" directory.

Do you have a tutorial on how to use this? I'm a bit clueless about using it! thanks

**Comment by lum8rjack** [comment]
This is just a caddy module that you can use as a proxy in front of Cobalt Strike. Instead of manually creating redirect rules to CS, this just reads the profile and redirects traffic based on the GET, POST, User-Agent, etc. The README has an example caddy config but here is also a blog post about the modules if it helps as well https://blog.lum8rjack.com/posts/caddy-c2/.

**Comment by notalkingya** [comment]
> This is just a caddy module that you can use as a proxy in front of Cobalt Strike. Instead of manually creating redirect rules to CS, this just reads the profile and redirects traffic based on the GET, POST, User-Agent, etc. The README has an example caddy config but here is also a blog post about the modules if it helps as well https://blog.lum8rjack.com/posts/caddy-c2/.

I see. I learned it. Thank you
